# Site Info
title: 'Somersby 공부 블로그'
tagline: 'Somersby 공부 블로그'
description: '프로그래밍 공부 블로그 입니다.'
baseurl: ""
url: https://somersbii.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Somersby
  description: Somersby
  contact:
    # linkedin:  <hide>
    github: https://github.com/somersbii
    #facebook:  <hide>
    # twitter:  <hide>
    # weibo:    <hide>
    email: mailto:somersby@kakao.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/blog/'
  Categories:
    - '/'
    - { Java: '/blog/categories/#java' }
    - { Servlet/JSP: '/blog/categories/#Servlet&JSP' }
    - { Database: '/blog/categories/#Database' }
    - { Project: '/blog/categories/#Project' }
    - { MDM: '/blog/categories/#MDM' }
    - { Android: '/blog/categories/#Android' }
    - { MacSetting: '/blog/categories/#Mac' }
    - { 알고리즘: '/blog/categories/#알고리즘' }
    - { etc: '/blog/categories/#etc' }
    # - { Tags: '/blog/tags/' }
  About:
    - '/about/'
  Search:
    - '/search/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'


# Puglins
mathjax: true # whether support mathjax
google_analytics_token: '' # leave blank if you don't want google analytics
disqus_short_name: 'somersbii-github-io' # leave blank if you don't want disqus
